### ISSUE TITLE
X-Series

### ISSUE THREAD

**Issue by relubbe** [kellerza/python-ids-alarm#2]
Have you tested your code on a X-series alarm? I've been trying to decode the keypad bus for some time now with almost no success.

I've tried your program, but aren't getting the "ready to arm" statuses like you do.

![capture - 2018-04-08](https://user-images.githubusercontent.com/38190278/38471269-fa6bef34-3b6e-11e8-886b-7d0a6a80b7ba.PNG)

**Comment by kellerza** [comment]
I never tested it on an X-Series. Even the code for the 1632 I never really got into a proper working state. In the end decoding was clearer using character 0 as the delimeter. Even when you can decode, you will still have a hard time to inject data into this bus.

For a time I was considering buying an X-Series and trying out the "Panel Serial Interface". Through the programming software it seems you can do most things. You can get it [here](http://www.rhinoco.com.au/file/download/96), but never had enough free time to justify buying a panel to try this out.

I've requested info on this serial interface from IDS and some distributors without any luck. The IDS1632 also has a Direct Download Interface, which might be similar to the serial interface, but never tried this either.

**Comment by vandyh** [comment]
I get exactly the same results from the x-series as relubbe. Have you made any progress since?

**Comment by kellerza** [comment]
Unfortunately not & have decided to abandon IDS altogether. Would have been nice to support a South African company, but in my case it would be spending money on IDS and then having to reverse engineer the protocols (and this method requires custom built 485 hardware as well)

The company/division creating the IDS IP module, called HYPP, don't respond to any requests for their API, so even that seems to be tied to their cloud implementation, which is a pity.

My advice would be buy a Paradox and integrate it like 100s of other people...

**Comment by clifforddw** [comment]
Agree it is a pity companies are so closed, you think they woudl realize if they made it easy for people to use there products, even in a maker application they would get more adoption. 

I also removed my IDS alarm and went for a DSC. They fully document their interface to the IT-100 [http://cms.dsc.com/download.php?t=1&id=16238](url) . Alternatively you can get a third part IP based module too that work really well, [http://www.eyezon.com/evl4.php](url)  both are available in SA. Be very careful of Paradox they have also been cutting off developer access on the local network.

**Comment by kellerza** [comment]
Thanks for the heads-up @clifforddw!

Seems that from v4 the Paradox IP150 now requires a SWAN server to connect to, so they cut off local connections

**Comment by kellerza** [comment]
### Paradox
There seems to be some hope for Paradox. I spoke to Abel from Paradox this morning and apparently from early Jan 2019 they enabled the option to accept local connections on the IP150 v4 again.

There is also a project with good traction to try out https://github.com/jpbarraca/pai/wiki - connections via local serial or the IP150 module (<v4 and >v4). If the serial is limited in any way I'll try the IP150 v4 with local network connection.

So Paradox is likely the correct route for me, it will also allow bus connection of my 4-5xNV780 sensors

### DSC
On the DSC front, the EVL4 you mentioned does not support the newer DSC Neo panels... they still have their official interface though, I did not investigate this in more detail.

### IDS
Tried to reach out to them various time. Dead end. **RIP IDS** (sad to say of an South African company)

### Konnected.io
Another interesting one is Konnected, they have a monitoring [device](https://konnected.io/collections/in-stock-now/products/konnected-alarm-panel-interface-for-wired-security-systems) for wired systems. Just not sure what lightning would do to their system & the other long term brands are rock solid when it comes to highveld weather...
