### ISSUE TITLE
how to read

### ISSUE THREAD

**Issue by tjoepies** [kellerza/python-ids-alarm#3]
hello, would this work with the IDS 805? 

[BSK USB RS485 TTL CONVERTER FTDI](https://www.communica.co.za/products/bsk-usb-rs485-ttl-converter-ftdi)

Would I only have to connect RX to D+ and TX to D-

**Comment by kellerza** [comment]
Hey @tjoepies it should work. RS485 is quite well defined/standard.

Don't expect too much from the library though... it's really an abandoned project from my side

**Comment by tjoepies** [comment]
Thank you for your contribution to the opensource community!

**Comment by relubbe** [comment]
I've managed to read data from the keypad bus using a RS-485 to USB converter. Problem is understanding the data. The installer manuals mention that communication is done using an IDS protocol.  And this protocol isn't available so we will not be able to decipher what is transfered over the bus.

I am currently using a LED keypad to do the translation for me. I've interfaced an arduino to the microcontroller IO pins on the keypad and let the keypad talk to the bus. So you can get data by reading the output pins and submit commands by driving the input pins.

Will post an update on my progress soon.

**Comment by kellerza** [comment]
Nice! An input should give you data to remove some of the guess work... If you have any say in the matter, I would go Paradox (1st choice) or DSC.

IDS makes nice products, but they are just too closed minded for this century. See also #2

**Comment by tjoepies** [comment]
I was hoping they use the modbus protocol

**Comment by e1ace** [comment]
Can you recall the port settings?

I keep getting Rx framing error with 19200 8 N 1

**Comment by kellerza** [comment]
@e1ace unfortunately not. From the code it seems to be 19200 baud, but I never continued work on this, as explained [here](https://github.com/kellerza/python-ids-alarm/issues/2#issuecomment-486716578)

My current Paradox SP6000 works exceptionally well and really a pity IDS is not open to integrate
